# Generated by Django 3.2.4 on 2021-06-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(1, 'Travel'), (2, 'Family'), (3, 'Lifestyle'), (4, 'Sports')], max_length=100),
        ),
    ]
