# Generated by Django 3.2.4 on 2021-07-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210705_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
